"""initial

Revision ID: 2bc1a47a3911
Revises: e1f5351376e9
Create Date: 2025-12-26 04:50:40.202404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc1a47a3911'
down_revision: Union[str, Sequence[str], None] = 'e1f5351376e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_summary', 'short_summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_summary', 'long_summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_summary', 'long_summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_summary', 'short_summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
