"""onboarding tables

Revision ID: 514a16ce17b1
Revises: abf6fadc7b29
Create Date: 2025-12-25 01:32:49.253124

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '514a16ce17b1'
down_revision: Union[str, Sequence[str], None] = 'abf6fadc7b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previous_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True)
    op.drop_index(op.f('ix_useronboarding_user_id'), table_name='useronboarding')
    op.drop_table('useronboarding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useronboarding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous_diseases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_symptoms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('additional_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('useronboarding_pkey'))
    )
    op.create_index(op.f('ix_useronboarding_user_id'), 'useronboarding', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_table('user_onboarding')
    # ### end Alembic commands ###
